<?php

/**
 * Implemenation of hook_context_load_alter()
 */
function archimedes_atrium_context_load_alter(&$context) {
  if (module_exists('atrium') && $context->name == 'spaces_dashboard-custom-1') {
    if (!isset($context->reactions['block']['blocks']['archimedes_og-activity'])) {
      $context->reactions['block']['blocks']['archimedes_og-activity'] = array(
        'module' => 'archimedes_og',
        'delta' => 'activity',
        'region' => 'content',
        'weight' => 0,
      );
    }
    if (!isset($context->reactions['block']['blocks']['views-applications-block_1'])) {
      $context->reactions['block']['blocks']['views-applications-block_1'] = array(
        'module' => 'views',
        'delta' => 'applications-block_1',
        'region' => 'right',
        'weight' => 0,
      );
    }
    $blacklist = array(
      'views-activity_listing-block_1',
      'atrium-welcome_member',
      'views-blog_comments-block_1',
    );
    foreach ($blacklist as $ns) {
      if (isset($context->reactions['block']['blocks'][$ns])) {
        unset($context->reactions['block']['blocks'][$ns]);
      }
    }
  }
}

