<?php

function archimedes_git_schema() {
  $schema['archimedes_git'] = array(
    'fields' => array(
      'nid' => array('type' => 'int', 'not null' => FALSE, 'unsigned' => TRUE),
      'repo_location' => array('type' => 'text', 'not null' => TRUE),
    ),
    'primary key' => array('nid'),
  );
  return $schema;
}

function archimedes_git_install() {
  drupal_install_schema('archimedes_git');
}

function archimedes_git_uninstall() {
  drupal_install_schema('archimedes_git');
}
